global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "sml_insurance_model"
    static_configs:
      - targets: ["localhost:9090"]   # port exporter

  - job_name: 'insurance_model_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'loan_model_api'

  - job_name: 'insurance_model_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8001']
        labels:
          service: 'insurance_model_exporter'

